Traceback (most recent call last):
  File "Apache_log_analysis.py", line 71, in ?
    logContentLength = line[9]
IndexError: list index out of range
